"""Tempered SMC identical-twin parameter recovery for the C-S-O box model.

This is an IDENTICAL-TWIN PARAMETER-RECOVERY demonstration, NOT a calibration to
real data and NOT a validation. There are NO proxy data here: the "observations"
are SYNTHETIC pseudo-observations generated by running the illustrative closed
carbon-sulfur-oxygen-alkalinity box model :mod:`eh_deeptime.carbon_sulfur` at a
KNOWN set of "true" parameters, then adding noise. We then run a tempered
Sequential Monte Carlo sampler over a small identifiable parameter subset and
check that the resulting posterior *brackets the known truth*. Recovering a truth
we put in by hand says the inference machinery works; it says nothing about the
real Earth and makes no claim of agreement with any measurement.

The sampler mirrors the structure of :mod:`eh_shallow.smc`:
  - particles drawn from the prior;
  - a geometric-ish inverse-temperature ladder beta: 0 -> 1 that introduces the
    pseudo-data gradually;
  - systematic resampling whenever ESS < N/2;
  - Gaussian random-walk MH rejuvenation with covariance matched to the cloud
    (scaled 2.38 / sqrt(d));
  - a Student-t(nu=4) likelihood, robust to outliers.

Identifiable subset (small, by design): ('ecs', 'f_degas', 'n_silw'). Climate
sensitivity 'ecs' is the best-identified, because the synthetic temperature
series responds to it almost one-for-one; 'f_degas' and 'n_silw' both modulate
the pCO2 peak and the recovery timescale and are only partly separable from a few
sampled points -- exactly the kind of weak-identifiability the SMC is meant to
expose rather than hide.

Three pseudo-observables are used jointly, each sampled at a handful of times in
the post-onset window: surface-temperature anomaly (K), log10 pCO2 (ppm) and the
DIC carbon-isotope ratio d13C (per mil). They are combined into a single
standardised residual with per-channel noise scales.

PRODUCTION SWAP: a research-grade version would (a) run blackjax/numpyro tempered
SMC on JAX, vectorised over particles, against COMPILED PROXY records (not
synthetic pseudo-data), with a full observational error model; and (b) sample the
full ~dozen-parameter vector with a structural-error term. None of that is done
here -- this is purely a self-consistency demonstration of the sampler.
"""
from __future__ import annotations

import numpy as np

from . import carbon_sulfur as cs

# --- likelihood / sampler constants ------------------------------------------
NU = 4.0                        # Student-t degrees of freedom (robust likelihood)

# Forward-run settings for both truth and particle evaluations (kept light so the
# whole demo runs offline in well under a minute).
T_END = 250.0                   # kyr, integration horizon
N_OUT = 101                     # output grid points
M_INJ = 4000.0                  # Gt C synthetic carbon release (illustrative)
T_DUR = 5.0                     # kyr, release duration
DELTA_INJ = -50.0               # per mil, injected-carbon d13C

# Times (kyr, post-onset) at which the SYNTHETIC pseudo-observations are sampled.
OBS_KYR = np.array([2.0, 10.0, 25.0, 50.0, 100.0, 150.0, 200.0])

# Per-channel synthetic-noise scales (also the likelihood sigmas). Illustrative,
# chosen to be a small fraction of the signal so the truth is recoverable.
SIGMA_TEMP = 0.30               # K, on the temperature-anomaly channel
SIGMA_LPCO2 = 0.03              # dex, on log10(pCO2/ppm)
SIGMA_D13C = 0.15               # per mil, on the DIC d13C channel

# Parameters inferred and their (broad, illustrative) priors. Truncated-Gaussian
# priors expressed as (mean, sd, lo, hi); 'ecs' and 'f_degas' are physically
# positive, 'n_silw' is a weathering exponent in (0, ~1.5).
PARAM_NAMES = ("ecs", "f_degas", "n_silw")
PRIOR = {
    "ecs":     (3.0, 1.2, 1.0, 6.0),    # K per CO2 doubling
    "f_degas": (1.0, 0.4, 0.4, 2.2),    # degassing multiplier
    "n_silw":  (0.8, 0.3, 0.3, 1.4),    # silicate-weathering pCO2 exponent
}

# Default "true" parameters for the twin experiment (inside the priors, off the
# prior means so a trivial prior-mean answer would fail).
DEFAULT_TRUTH = {"ecs": 4.0, "f_degas": 0.85, "n_silw": 0.65}


def _theta_to_params(theta_row):
    """Map a particle row [ecs, f_degas, n_silw] to a carbon_sulfur params dict."""
    return {name: float(v) for name, v in zip(PARAM_NAMES, theta_row)}


def _forward_obs(params):
    """Run the box model and return the model values at the OBS_KYR sample times.

    Returns a flat residual-space vector [temp(K)..., log10 pCO2..., d13c...].
    """
    res = cs.run_csys(params=params, m_inj=M_INJ, t_dur=T_DUR,
                      delta_inj=DELTA_INJ, t_end=T_END, n_out=N_OUT)
    kyr = res["kyr"]
    temp = np.interp(OBS_KYR, kyr, res["temp"])
    lpco2 = np.log10(np.interp(OBS_KYR, kyr, res["pco2"]))
    d13c = np.interp(OBS_KYR, kyr, res["d13c"])
    return np.concatenate([temp, lpco2, d13c])


def _sigma_vector():
    """Per-element noise/likelihood sigma matching the _forward_obs layout."""
    n = len(OBS_KYR)
    return np.concatenate([
        np.full(n, SIGMA_TEMP),
        np.full(n, SIGMA_LPCO2),
        np.full(n, SIGMA_D13C),
    ])


def make_pseudo_obs(truth, rng):
    """Generate SYNTHETIC pseudo-observations at the known truth.

    The clean model output at `truth` is corrupted with Student-t(nu=NU) noise
    scaled by the per-channel sigmas. These are NOT real data; they exist only so
    the sampler has something to recover. Returns (y_obs, sigma).
    """
    clean = _forward_obs(truth)
    sigma = _sigma_vector()
    # Student-t noise: standard-t draws scaled to unit-ish variance then by sigma.
    noise = rng.standard_t(NU, size=clean.shape) * np.sqrt((NU - 2.0) / NU)
    return clean + sigma * noise, sigma


def _log_prior(theta):
    """Truncated-Gaussian log-prior over the particle array [n, d] (up to const)."""
    lp = np.zeros(len(theta))
    for j, name in enumerate(PARAM_NAMES):
        mu, sd, lo, hi = PRIOR[name]
        x = theta[:, j]
        lp += -0.5 * ((x - mu) / sd) ** 2
        lp = np.where((x >= lo) & (x <= hi), lp, -np.inf)
    return lp


def _sample_prior(rng, n):
    """Draw n particles from the truncated-Gaussian prior."""
    theta = np.empty((n, len(PARAM_NAMES)))
    for j, name in enumerate(PARAM_NAMES):
        mu, sd, lo, hi = PRIOR[name]
        col = np.empty(n)
        filled = 0
        while filled < n:
            draw = rng.normal(mu, sd, size=2 * (n - filled) + 8)
            draw = draw[(draw >= lo) & (draw <= hi)]
            take = min(len(draw), n - filled)
            col[filled:filled + take] = draw[:take]
            filled += take
        theta[:, j] = col
    return theta


def _loglik_factory(y_obs, sigma):
    """Return loglik(theta_arr)->[n], the joint Student-t(nu=NU) log-likelihood."""
    inv_sigma = 1.0 / sigma

    def loglik(theta_arr):
        out = np.empty(len(theta_arr))
        for i, th in enumerate(theta_arr):
            try:
                model = _forward_obs(_theta_to_params(th))
            except Exception:
                out[i] = -1e30
                continue
            r = (model - y_obs) * inv_sigma
            # Student-t log density (constants dropped; they cancel across particles)
            out[i] = float(np.sum(-0.5 * (NU + 1.0) * np.log1p(r ** 2 / NU)))
        return out

    return loglik


def _ess(logw):
    w = np.exp(logw - logw.max())
    w /= w.sum()
    return 1.0 / np.sum(w ** 2), w


def _systematic_resample(w, rng):
    n = len(w)
    positions = (rng.random() + np.arange(n)) / n
    idx = np.searchsorted(np.cumsum(w), positions)
    return np.clip(idx, 0, n - 1)


def run_smc(n_particles=400, n_temps=10, n_rejuv=4, seed=0,
            truth=None, verbose=False):
    """Run tempered SMC identical-twin parameter recovery on synthetic pseudo-data.

    Parameters
    ----------
    n_particles : int    number of SMC particles
    n_temps : int        length of the beta: 0 -> 1 inverse-temperature ladder
    n_rejuv : int        MH rejuvenation steps per temperature
    seed : int           RNG seed (fixed for reproducibility)
    truth : dict | None  the "true" params to recover (DEFAULT_TRUTH if None)
    verbose : bool       print per-temperature ESS

    Returns
    -------
    dict with keys 'theta' [n,d], 'weights' [n], 'names', 'truth' (array, in
    PARAM_NAMES order), 'loglik' [n], 'log' (list of per-temperature diagnostics).
    The posterior is meant to BRACKET the known truth -- this is a sampler
    self-consistency check, not a calibration.
    """
    rng = np.random.default_rng(seed)
    truth_d = dict(DEFAULT_TRUTH)
    if truth:
        truth_d.update(truth)
    truth_arr = np.array([truth_d[n] for n in PARAM_NAMES])

    y_obs, sigma = make_pseudo_obs(truth_d, rng)
    loglik = _loglik_factory(y_obs, sigma)

    theta = _sample_prior(rng, n_particles)
    ll = loglik(theta)
    betas = np.linspace(0.0, 1.0, n_temps) ** 2  # denser near 0
    logW = np.zeros(n_particles)   # accumulated log unnormalised SMC weights
    log = []

    for t in range(1, n_temps):
        dbeta = betas[t] - betas[t - 1]
        # accumulate the incremental tempering weight across steps, then normalise.
        # Carrying logW between temperatures (and resetting it to uniform only when
        # a resample fires) is what makes this a valid tempered-SMC estimator.
        logW = logW + dbeta * ll
        ess, w = _ess(logW)
        log.append({"beta": float(betas[t]), "ess": float(ess)})
        if verbose:
            print(f"  beta={betas[t]:.3f}  ESS={ess:6.1f}/{n_particles}")
        if ess < n_particles / 2:
            idx = _systematic_resample(w, rng)
            theta, ll = theta[idx], ll[idx]
            logW = np.zeros(n_particles)   # weights reset to uniform after resample
        # MH rejuvenation at the current tempered target (prior + beta*ll); the
        # MCMC moves leave the importance weights unchanged.
        cov = np.cov(theta.T) + 1e-9 * np.eye(theta.shape[1])
        L = np.linalg.cholesky(cov) * 2.38 / np.sqrt(theta.shape[1])
        lp = _log_prior(theta) + betas[t] * ll
        for _ in range(n_rejuv):
            prop = theta + (rng.standard_normal(theta.shape) @ L.T)
            lp_prior_prop = _log_prior(prop)
            # only evaluate the (expensive) likelihood where the prior is finite
            finite = np.isfinite(lp_prior_prop)
            ll_prop = np.full(n_particles, -np.inf)
            if np.any(finite):
                ll_prop[finite] = loglik(prop[finite])
            lp_prop = lp_prior_prop + betas[t] * ll_prop
            accept = np.log(rng.random(n_particles)) < (lp_prop - lp)
            theta[accept] = prop[accept]
            ll[accept] = ll_prop[accept]
            lp[accept] = lp_prop[accept]

    # final posterior weights are the accumulated weights at beta = 1 (uniform if
    # the last temperature resampled); no extra increment is re-applied.
    _, w = _ess(logW)

    return {
        "theta": theta, "weights": w, "names": PARAM_NAMES,
        "truth": truth_arr, "loglik": ll, "log": log,
        "y_obs": y_obs, "sigma": sigma, "obs_kyr": OBS_KYR, "seed": seed,
    }


def posterior_summary(post):
    """Weighted mean and 5-95% interval for each inferred parameter."""
    theta, w = post["theta"], post["weights"]
    out = {}
    for j, name in enumerate(post["names"]):
        x = theta[:, j]
        order = np.argsort(x)
        cw = np.cumsum(w[order])
        lo = x[order][np.searchsorted(cw, 0.05)]
        hi = x[order][min(np.searchsorted(cw, 0.95), len(x) - 1)]
        out[name] = {"mean": float(np.sum(w * x)),
                     "p05": float(lo), "p95": float(hi)}
    return out
